/* Fouques’t Suite v9.1 — Pro PWA (GitHub Pages) — app.js v3 */
const DEFAULT_CONFIG = {
  apiBaseUrl: 'https://script.google.com/macros/s/AKfycbx_aTmsQpsA5bf94EiZyGHjsn36M5lYl0Ig1QtxxJVbuT_UnTQWTmWQZeojRB7jB3q1/exec',
  apiKey: localStorage.getItem('fs_key') || '',
};
function appState(){
  return {
    tab:'home',
    deferredPrompt:null,
    online: navigator.onLine,
    whoami:{ email:null, role:null },
    kpi:{ pertes7j:0, valeurStock:0, topPerdu:'-', progressMensuel:0, pertes7jSeries:[] },
    templates:[],
    zones: ['CF Poisson','CF Viande','Economat','Congélateur 1','Congélateur 2'],
    recettes: { query:'', mult:1, items:[] },
    rapports: { periode:'', type:'pdf_mensuel' },
    perte: { produit:'', qte:null, unite:'', motif:'', zone:'' },
    perteStatus:'',
    journalier: { selection:'', qte:null },
    journalierStatus:'',
    mensuel: { zone:'', action:'brouillon' },
    mensuelStatus:'',
    rapportsStatus:'', rapportUrl:'',
    config: { apiBaseUrl: localStorage.getItem('fs_api') || DEFAULT_CONFIG.apiBaseUrl, apiKey: localStorage.getItem('fs_key') || DEFAULT_CONFIG.apiKey },
    toast: { show:false, msg:'' },
    toastMsg(m){ this.toast.msg=m; this.toast.show=true; setTimeout(()=>this.toast.show=false, 2000); },
    saveConfig(){ localStorage.setItem('fs_api', this.config.apiBaseUrl||''); localStorage.setItem('fs_key', this.config.apiKey||''); this.toastMsg('✓ Enregistré'); },
    async init(){ window.addEventListener('beforeinstallprompt', (e)=>{ e.preventDefault(); this.deferredPrompt = e; }); window.addEventListener('online', ()=>{ this.online=true; }); window.addEventListener('offline', ()=>{ this.online=false; }); await this.refreshAll(); this.drawCharts(); },
    async refreshAll(){ await this.loadWhoAmI(); await this.refreshKPI(); await this.loadTemplates(); await this.loadRecettes(); },
    formatCurrency(v){ try{ return new Intl.NumberFormat('fr-FR', {style:'currency', currency:'EUR'}).format(v||0); }catch(e){ return (v||0)+' €'; } },
    async apiGet(path){ const base=this.config.apiBaseUrl.replace(/\/+$/,''); const p=(path||'').replace(/^\//,''); const r=await fetch(`${base}?path=${encodeURIComponent(p)}`,{ headers:{ 'X-API-Key': this.config.apiKey } }); return r.json(); },
    async apiPost(path, body){ const base=this.config.apiBaseUrl.replace(/\/+$/,''); const p=(path||'').replace(/^\//,''); const r=await fetch(`${base}?path=${encodeURIComponent(p)}`,{ method:'POST', headers:{ 'Content-Type':'application/json', 'X-API-Key': this.config.apiKey }, body: JSON.stringify(body||{}) }); return r.json(); },
    async loadWhoAmI(){ try{ const j=await this.apiGet('whoami'); if(j.ok) this.whoami=j.data; }catch(_ ){} },
    async refreshKPI(){ try{ const j=await this.apiGet('kpi'); if(j.ok) this.kpi=j.data; }catch(_ ){} },
    async loadTemplates(){ try{ const j=await this.apiGet('templates'); if(j.ok) this.templates=j.data; }catch(_ ){} },
    async loadRecettes(){ try{ const j=await this.apiGet('recettes'); if(j.ok) this.recettes.items=j.data||[]; }catch(_ ){} },
    filteredRecettes(){ const q=(this.recettes.query||'').toLowerCase().trim(); if(!q) return this.recettes.items; return this.recettes.items.filter(r => (r.nom||'').toLowerCase().includes(q) || (r.categorie||'').toLowerCase().includes(q) || (r.allergenes||'').toLowerCase().includes(q)); },
    scaleIngredients(ings){ const m=this.recettes.mult||1; return (ings||[]).map(it=>({...it, qte: Math.round((it.qte*m)*1000)/1000})); },
    async submitPerte(){ this.perteStatus='…'; try { if (!this.perte.produit || !this.perte.qte || this.perte.qte<=0 || !this.perte.unite) throw new Error('Champs invalides'); const j = await this.apiPost('mouvement', { type:'PERTE', ...this.perte }); if (!j.ok) throw new Error(j.error||'Erreur'); this.perte={ produit:'', qte:null, unite:'', motif:'', zone:'' }; this.perteStatus='✅ Perte enregistrée'; this.refreshKPI(); } catch(e){ this.perteStatus='❌ '+e.message; } },
    async submitMouvement(){ this.journalierStatus='…'; try { const t=this.templates.find(x=>x.code===this.journalier.selection); if(!t) throw new Error('Sélection invalide'); if(!this.journalier.qte || this.journalier.qte<=0) throw new Error('Quantité invalide'); const j=await this.apiPost('mouvement', { type:t.flux||'MVT', produit:t.produit, qte:this.journalier.qte, unite:t.unite, motif:t.flux, zone:t.zone||'' }); if (!j.ok) throw new Error(j.error||'Erreur'); this.journalier={ selection:'', qte:null }; this.journalierStatus='✅ Mouvement enregistré'; this.refreshKPI(); } catch(e){ this.journalierStatus='❌ '+e.message; } },
    async doMensuelAction(){ this.mensuelStatus='…'; try { if(!this.mensuel.zone) throw new Error('Choisir une zone'); const j=await this.apiPost('inventaire-mensuel', this.mensuel); if(!j.ok) throw new Error(j.error||'Erreur'); this.mensuelStatus='✅ OK'; this.refreshKPI(); } catch(e){ this.mensuelStatus='❌ '+e.message; } },
    async produire(recette){ try { const j=await this.apiPost('produire', { recetteId:recette.id, mult:this.recettes.mult||1 }); if(!j.ok) throw new Error('Erreur prod'); alert('✓ Production enregistrée'); this.refreshKPI(); } catch(e){ alert('❌ '+e.message); } },
    async genererRapport(){ this.rapportsStatus='…'; this.rapportUrl=''; try { if(!this.rapports.periode) throw new Error('Choisir une période (AAAA-MM)'); const j=await this.apiPost('rapport', this.rapports); if(!j.ok) throw new Error('Erreur rapport'); this.rapportsStatus='✅ Généré'; if(j.data?.url) this.rapportUrl=j.data.url; } catch(e){ this.rapportsStatus='❌ '+e.message; } },
    drawCharts(){ const el=document.getElementById('chartPertes'); if(!el||!window.Chart) return; const labels=(this.kpi.pertes7jSeries||[]).map(x=>x.date); const data=(this.kpi.pertes7jSeries||[]).map(x=>x.kg); new Chart(el, { type:'line', data:{ labels, datasets:[{ label:'kg', data, tension:.35, fill:true }] }, options:{ responsive:true, maintainAspectRatio:false, plugins:{ legend:{ display:false } } } }); },
  };
}
